include::_include_all.adoc[]

:sectnums: 4
:toclevels: 6

[[Intro]]
= 導入

[[Intro_Goal]]
== {GL}の目的

{GL}では{SB}に関する説明およびチュートリアルを提供し、実際のアプリケーション開発を通して読者が{SB}の特徴やメリットを理解できることを目的とする。

そのため、{SB}の機能を網羅的に説明しているわけではない。{GL}で説明していない機能や使い方に関しては {reference_url}[{SB}の公式リファレンス] を参照すること。

{GL}を読むことで{SB}の技術習得および{SB}を使用したソフトウェア開発が円滑に進むことを期待する。

[[Intro_TargetReaders]]
== 対象読者

{GL}はソフトウェア開発経験のあるアーキテクトやプログラマ向けに書かれており、下記の知識があることを前提としている。

* {SF}のDIやAOPに関する基礎的な知識がある
* {SM}に関する基礎的な知識がある
* Javaを使用してアプリケーションを開発したことがある
* JUnitに関する基礎的な知識がある
* SQLに関する知識がある
* O/R Mapper(JPA、MyBatisなど)に関する知識がある
* Mavenを使用したことがある

これからJavaを勉強し始めるという人向けではない。

[[Intro_Structure]]
== {GL}の構成

ifeval::["{docname}" != "single_index"]

<<SpringBoot_basics.adoc#Basics,{SB}の基本>>::
  {SB}の概要と{SB}の適用に向いたシステムについて説明する。

<<SpringBoot_architecture.adoc#Architecture,{SB}の主要な機能>>::
  {SB}を構成する{SBA}、{ES}、{EJ}などについて説明する。

<<Tutorial.adoc#Tutorial,チュートリアル>>::
  基本的なWebアプリケーション開発をとおして、{SB}によるアプリケーション開発を体験する。

<<function_index.adoc#function,機能紹介>>::
  {SB}を使用してアプリケーション開発で実装するアプリケーションの各機能や関連ライブラリの使用方法について説明する。

endif::[]

ifeval::["{docname}" == "single_index"]

<<Basics,{SB}の基本>>::
  {SB}の概要と{SB}の適用に向いたシステムについて説明する。

<<Architecture,{SB}の主要な機能>>::
  {SB}を構成する{SBA}、{ES}、{EJ}などについて説明する。

<<Tutorial,チュートリアル>>::
  基本的なWebアプリケーション開発をとおして、{SB}によるアプリケーション開発を体験する。

<<function,機能紹介>>::
  {SB}を使用してアプリケーション開発で実装するアプリケーションの各機能や関連ライブラリの使用方法について説明する。

endif::[]

[[Intro_HowToRead]]
== {GL}の読み方

ifeval::["{docname}" != "single_index"]

<<SpringBoot_basics.adoc#Basics,{SB}の基本>>::
上記のコンテンツは{SB}を使用するすべての開発者が読むことを推奨する。

<<SpringBoot_architecture.adoc#Architecture,{SB}の主要な機能>>::
上記のコンテンツは{SB}の仕組みを理解するために読んでおくべきである。 +
{SB}を使った開発でトラブルシューティングを行うためには、{SB}の仕組みを理解しておく必要があり、一部実装面に踏み込んだ細かい説明となっている。 +
難易度が高いと感じる場合は、先に<<Tutorial.adoc#Tutorial,チュートリアル>>を実施して{SB}に対する理解度を上げてから読み直すとよい。

<<Tutorial.adoc#Tutorial,チュートリアル>>::
上記のコンテンツは{SB}を使用して実際のアプリケーション開発を体験したい開発者が読むことを推奨する。 +
はじめて{SB}に触れる場合は、まずこのコンテンツから読み始め、他のコンテンツを参照しながら進めるとよい。

<<function_index.adoc#function,機能紹介>>::
上記のコンテンツは必要に応じて参照すればよい。

endif::[]

ifeval::["{docname}" == "single_index"]

<<Basics,{SB}の基本>>::
上記のコンテンツは{SB}を使用するすべての開発者が読むことを推奨する。

<<Architecture,{SB}の主要な機能>>::
上記のコンテンツは{SB}の仕組みを理解するために読んでおくべきである。 +
{SB}を使った開発でトラブルシューティングを行うためには、{SB}の仕組みを理解しておく必要があり、一部実装面に踏み込んだ細かい説明となっている。 +
難易度が高いと感じる場合は、先に<<Tutorial,チュートリアル>>を実施して{SB}に対する理解度を上げてから読み直すとよい。

<<Tutorial,チュートリアル>>::
上記のコンテンツは{SB}を使用して実際のアプリケーション開発を体験したい開発者が読むことを推奨する。 +
はじめて{SB}に触れる場合は、まずこのコンテンツから読み始め、他のコンテンツを参照しながら進めるとよい。

<<function,機能紹介>>::
上記のコンテンツは必要に応じて参照すればよい。

endif::[]

[[Intro_HowToRead_representation]]
=== {GL}での表記

{GL}での表記について、留意事項を述べる。

WindowsコマンドプロンプトとUnix系ターミナルについて::
WindowsとUnix系の表記の違いで動作しなくなる場合は併記する。
そうでない場合は、Unix系の表記で統一する。

プロンプト記号::
Unix系の``$``にて表記する。

[source,console]
.プロンプト表記例
----
$ java -version
----

コメント記号::
Unix系の``\#``にて表記する。 +
なお、{GL}では、root権限でコマンドを実行することはなく、``#``はコメント記号としてのみ扱う。

[source,console]
.コメント表記例
----
$ # 行頭コメント
$ java -version # 行末コメント
----

注釈の凡例::
{GL}で記載する注釈表記の凡例を下記に示す。

[NOTE]
.NOTE
====
補足説明について記す。
====

[TIP]
.TIP
====
簡単な拡張方法や参考資料などについて記す。
====

[IMPORTANT]
.IMPORTANT
====
順守すべき事など重要事項について記す。
====

[WARNING]
.WARNING
====
間違えやすい内容など注意すべき事項について記す。
====

[CAUTION]
.CAUTION
====
問題を引き起こしかねない設定や実装など非推奨事項について記す。
====

[[Intro_TestedEnvironments]]
== 検証環境

{GL}における記載内容の検証を行った環境条件を下記に示す。

[cols="20,80", options="header"]
.環境条件
|===
|ソフトウェア
|バージョン

|{SB}
|{spring_integration_version}

|JDK
|openjdk 11.0.3-internal 2019-04-16

|Apache Maven
|3.6.2

|Spring Tool Suite
|4.3.2.RELEASE
|===
