include::_include_all.adoc[]

:sectnums: 4
:toclevels: 6

[[Basics]]
= {SB}の基本

[[Basics_Introduction]]
== {SB}とは

{SB}とは、Springプロジェクトの1つであり、{SF}を使用したスタンドアロンで即実行可能なアプリケーションを作成可能なフレームワークである。

ここでは、{SB}について下記の流れで説明する。

* <<Basics_Introduction_SpringFrameworkIssues>>
* <<Basics_Introduction_Overview>>
* <<Basics_Introduction_Considerations>>

[[Basics_Introduction_SpringFrameworkIssues]]
=== {SF}の課題と{SB}

現在、Springプロジェクトは{SF}を中心に、20以上のさまざまな有用な機能を提供するプロジェクトが存在しており、大きなエコシステムを形成している。
{SF}でのアプリケーション開発では、これらの機能を適切に組み合わせて1つのアプリケーションを作ることになる。 +

しかし、{SF}を用いた一般的なアプリケーション開発において、下記のような課題がある。

* 設定が煩雑で難しいため、どのような設定をすればよいのかわからない
* 小規模なアプリケーションの開発においても最初のセットアップが大変である
* 各プロジェクトおよびライブラリをどう組み合わせてよいのかわからない
* どのライブラリのどのバージョンを使えばよいかわからない
* アプリケーションサーバのセットアップやアプリケーションのデプロイする作業が必要となる

これらの課題は、{GL}で紹介する「{SB}」を使用することで解決することができる。

[[Basics_Introduction_Overview]]
=== {SB}の概要

{SB}は2013年に開発が始まり、2014年4月にバージョン1.0、2018年3月にバージョン2.0.0がリリースされ、執筆時点(2019年12月)のバージョンは2.2.0.RELEASEである。
{SB}はバージョンアップとともに便利な機能が追加され続けており、幅広い分野のエンタープライズアプリケーション構築で採用されている。

{SB}は主に下記の4つの特徴によって{SF}の課題を克服し、アプリケーションの開発を助けている。 +
それぞれの課題に対する{SB}の機能については、<<SpringBoot_architecture.adoc#Architecture,{SB}の主要な機能>>で説明する。

依存ライブラリを定義するだけで{SB}が自動で設定を反映する::
{SB}を使用すると、依存ライブラリを定義するだけでオススメの設定が反映されるため開発者が設定を記述することなくデフォルトの状態でさまざまな機能を利用できる。
これによって、{SB}を使用しないアプリケーション開発で必要であったXMLまたはJava ConfigによるBean定義、ログの設定、Servletの設定などが大幅に削減される。
これは、{SBA}という機能が実現している。 +
詳細は、<<SpringBoot_architecture.adoc#Architecture_AutoConfiguration,「{SB}の主要な機能」の{SBA}>>で説明する。

Starterを指定するだけで{SB}が必要となるライブラリを自動で設定する::
{SB}では、使用したい機能のStarterを指定するだけで、必要となるライブラリに関する設定を自動的に行われる。
そのため、開発者が細かいライブラリの選定やライブラリのバージョン指定といった作業を行うことなく、様々な機能を使用することができる。 +
詳細は、<<SpringBoot_architecture.adoc#Architecture_Starter,「{SB}の主要な機能」のStarterによる依存ライブラリの解決>>で説明する。

アプリケーションをサーバにデプロイする必要はなく、{ES}で実行する::
{SB}はアプリケーションサーバを内包しているためデプロイする必要もなくなり、Javaのmainメソッドを実行すればアプリケーションを実行できる。
これによって、多くの開発者が煩わしい作業だと感じていたアプリケーションサーバのセットアップやアプリケーションをデプロイする作業が不要になる。 +
詳細は、<<SpringBoot_architecture.adoc#Architecture_Run_EmbeddedServer,「{SB}の主要な機能」の{ES}>>で説明する。

{EJ}形式でパッケージングすることでアプリケーションを即実行可能とする::
{SB}を使用すると、依存ライブラリを内包した即実行可能なJar形式で、アプリケーションをパッケージングできるため、1つのコマンドを実行するだけで簡単にアプリケーションを実行できる。 +
また、プロパティやプロファイルを実行時にコマンドライン引数や環境変数で指定できるため、実行時にアプリケーションの動作を柔軟に変更することもできる。 +
詳細は、<<SpringBoot_architecture.adoc#Architecture_Run_ExecutableJar,「{SB}の主要な機能」の{EJ}>>で説明する。

{SB}は上記以外にも開発作業をサポートする{DT}、メトリクス収集やヘルスチェックを行うためのエンドポイントを提供する{SB} Actuator、テストをサポートする機能など様々な機能を提供している。 +
また、パッケージ構成や依存ライブラリ、プラグインなどの設定を行った{SB}プロジェクトを生成することができる{SI}というWebサービスを提供しており、簡単にアプリケーション開発を開始することができる。

各機能の詳細は以降の章や {reference_url}[{SB}の公式リファレンス] を参照すること。

[[Basics_Introduction_Considerations]]
=== 従来の{SF}を用いたアプリケーション開発との違い

{SB}は、自動で設定を反映する{SBA}、{ES}、{EJ}、開発作業やテストをサポートする機能を提供している。
アプリケーションの機能開発には変わらず{SF}を使用するため、従来の{SF}を用いたアプリケーション開発と同様に{SF}の知識が必要であり、基本的な実装内容は変わらない。

以下に{SB}を用いたアプリケーション開発と従来の{SF}を用いたアプリケーション開発との違いについて説明する。

{SI}を使用することで簡単にアプリケーション開発を開始することができる::
{SI}とは、パッケージ構成、依存ライブラリ、プラグインなどの設定を行った{SB}プロジェクトを生成することができるWebサービスである。
{SI}を使用することで、従来の{SF}を用いたアプリケーション開発で必要だった煩雑で難しい設定は不要となる。
+
{SI}に関しては、<<SpringBoot_architecture.adoc#Architecture_SpringInitializr,{SI}による{SB}プロジェクトの作成>>を参照すること。

{SBA}によってアプリケーションの設定が大幅に削減される。::
{SBA}によって、アプリケーションの設定(Bean定義、ログの設定、Servletの設定など)が大幅に削減される。
しかし、{SB}から提供されていないサードパーティのライブラリを使用する場合や、{SBA}が適用する設定をカスタマイズしたい場合には開発者が設定を行う必要がある。
+
{SBA}に関しては、<<SpringBoot_architecture.adoc#Architecture_AutoConfiguration,{SBA}>>を参照すること。

{SB}が提供する{ES}やテストをサポートする機能によりテスト効率が向上する::
{SB}は、テストに使用するBeanを自動生成するアノテーションなど、アプリケーションの単体テスト/結合テストをサポートする機能を提供している。
また、{SB}はアプリケーションサーバを内包しているためデプロイする必要がなくなりテスト効率が向上する。
+
テスト関連の機能に関しては、<<SpringBoot_architecture.adoc#Architecture_Test,{SB}のテスト関連機能>>を、{ES}に関しては、<<SpringBoot_architecture.adoc#Architecture_Run_EmbeddedServer,{ES}>>を参照すること。

{ES}で起動するアプリケーションが{EJ}形式でパッケージングされるためリリース手順が簡略化される::
{SB}はアプリケーションサーバを内包しているためアプリケーションサーバにデプロイする必要がない。また、{EJ}は1つのコマンドを実行するだけで簡単にアプリケーションを実行できる。
そのため、{SB}を使用したアプリケーション開発では、従来の{SF}を用いたアプリケーション開発に比べてリリース手順が簡略化される。
+
{ES}に関しては、<<SpringBoot_architecture.adoc#Architecture_Run_EmbeddedServer,{ES}>>を、{EJ}については、<<SpringBoot_architecture.adoc#Architecture_Run_ExecutableJar,{EJ}>>を参照すること。

[[Basics_RequirementsToFit]]
== 適用に向いたシステム

{SB}は<<Basics_Introduction_Overview>>で説明した特徴と開発をサポートする機能をもつため、以下のようなシステムの開発に向いている。 +
これらはあくまでも指針であるため、{SB}の主要な機能を理解した上で{SB}メリットを享受できるのかを軸に適用要否を検討すること。

{SB}の自動設定に合致し、複雑なカスタマイズが必要ないシステム::
{SB}は、依存ライブラリを定義するだけでオススメの設定を反映し、開発者が設定を記述する作業を削減する。
これは{SB}の大きなメリットであり設定がシンプルになる反面、設定を反映する機能である{SBA}の構造は複雑なものとなっている。 +
そのため、カスタマイズを行う際には、{SBA}によるカスタマイズ要件の制約や{SF}のカスタマイズに比べて難易度があがってしまう点に注意すること。
+
例えば、既存システムからの移行を行う場合に{SB}がデフォルトで対応していない仕様(Java EEの仕様)をカスタマイズによって実現する場合には、カスタマイズが可能であるか十分に検証が必要である。
{SB}の主要な機能に関しては、<<SpringBoot_architecture.adoc#Architecture,{SB}の主要な機能>>を参照すること。

テスト駆動開発を行うシステム::
{SB}はテスト関連の機能を提供しており、簡単な設定のみでアプリケーションの単体テスト/結合テストを実装することができる。
そのため、テスト駆動開発を行うシステム開発では、より{SB}のメリットを享受することができる。 +
{SB}のテスト関連の機能に関しては、<<SpringBoot_architecture.adoc#Architecture_Test,{SB}のテスト関連機能>>を参照すること。

スケーリングやクラスタ化が必要な大規模なシステム::
{SB}は、Springプロジェクトやサードパーティのライブラリと連携するシステムを簡単に構築することができる。
複数のサービスと連携が必要となる、スケーリングやクラスタ化が必要な大規模なシステムの構築に{SB}は向いているといえる。
たとえば、{SI}にて{SWS}、{SS}、{SDR}を選択することで、基本的な設定が反映済みのスケーラブルなアプリケーションのプロジェクトを作成して開発を進めることができる。 +
{SI}に関しては、<<SpringBoot_architecture.adoc#Architecture_SpringInitializr,{SI}による{SB}プロジェクトの作成>>を参照すること。

迅速な仕様変更などアジリティを求められるシステム::
{SB}は、開発作業をサポートする{DT}やテスト関連の機能を提供しており、アプリケーション開発作業からのテストまで効率的に行うことができる。 +
また、{EJ}によってパッケージング形式および実行方法もシンプルであるため、CI/CDと親和性が高いといえる。
そのため、{SB}は迅速な仕様変更などアジリティを求められるシステムに向いているといえる。

[[Basics_RequirementsToFit_Microservices]]
=== マイクロサービスアーキテクチャとの親和性

マイクロサービスアーキテクチャとは、粒度が細かく自律的に動作するアプリケーションを組み合わせてシステムを構築するアーキテクチャのことである。

「マイクロサービス」という言葉は、James Lewis氏が2012年に発表した http://2012.33degree.org/talk/show/67[33rd Degree - Conference for Java Masters - Micro services - Java, the Unix Way] にて初めて使われたといわれている。 +
また、James Lewis氏とMartin Fowler氏が2014年に発表した https://martinfowler.com/articles/microservices.html[Microservices - martinFowler.com] という記事で「マイクロサービス」について詳細に述べられている。 +
マイクロサービスについての詳しい説明は{GL}では説明しない、詳しい説明は上記のリンク先を参照すること。

{SB}は、 http://2012.33degree.org/talk/show/67[33rd Degree - Conference for Java Masters - Micro services - Java, the Unix Way] にて定義されているマイクロサービスアーキテクチャのほとんどの要素を満たしているため、マイクロサービスアーキテクチャとの親和性が高いといえる。

マイクロサービスアーキテクチャの要素の内、{SB}が要素を満たしているものを{SB}の特徴・機能とともに以下に示す。

Small with a single responsibility::
* 各アプリケーションは1つの機能だけをもつ
* すべて頭に入る程に小さい
* いつでも捨てることができる程に小さい

{SB}は、<<Basics_Introduction_Overview>>で説明したとおり、目的に応じたStarterや依存ライブラリを指定することによって、アプリケーションの設定にかかる時間を削減できる。
そのため、{SB}は小規模なアプリケーションを迅速に開発しデプロイするのに向いているといえる。

Containerless and installed as well behaved Unix services::
* 組み込みWebコンテナ(テスト容易性、デプロイ容易性が向上する)
* {EJ}形式でのパッケージング、Unixのサービススクリプトでの実行

{SB}は、アプリケーションサーバを内包し、アプリケーションを{EJ}形式でパッケージングすることができる。また、作成した{EJ}はUnixのサービススクリプトに登録して実行することもできる。
詳細は、 {reference_url}#deployment-service[{SB}の公式リファレンス] を参照すること。

Located in different VCS roots::
* 各アプリケーションは完全に独立している
* 共通モジュールはライブラリとして作成・使用する

マイクロサービスアーキテクチャを構成する各アプリケーションを独立したVCSで管理するためには、各アプリケーションで個別に設定が必要となる。
{SB}には、目的に応じたStarterが用意されているため、アプリケーションの設定が単純化され、管理が容易となる。
また、共通モジュールを依存ライブラリとして指定することも可能である。

Status aware and auto-scaling::
* 各アプリケーションがヘルスチェック、メトリクスの収集に対応している

{SB}は、ヘルスチェックやメトリクスの収集などに対応する{SB} Actuatorという機能を提供している。
